  CREATE TABLE "UPD"."UPD_PCBA_PGM_IMEI" 
   (	"SERIAL_NO" VARCHAR2(50 BYTE), 
	"MARKET_NAME" VARCHAR2(100 BYTE), 
	"MODEL_NUMBER" VARCHAR2(100 BYTE), 
	"REQUEST_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"REQUESTER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"GENERATION_DATE" DATE NOT NULL ENABLE, 
	"GPPD_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CUSTOMER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PROGRAMMING_FACILITY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"BUILD_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"PRODUCT_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"DISPATCH_DATE" DATE, 
	"DISPATCH_STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
	"RSD_ID" VARCHAR2(50 BYTE), 
	"MASC_ID" VARCHAR2(50 BYTE), 
	"CLIENT_REQUEST_DATETIME" DATE, 
	"CREATED_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"CREATED_DATETIME" DATE NOT NULL ENABLE, 
	"LAST_MOD_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"LAST_MOD_DATETIME" DATE NOT NULL ENABLE, 
	"PGM_DATE" DATE, 
	"PGM_STATUS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
	"SWAP_DATE" DATE, 
	"PCBA_ASSEMBLY_PTNO" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK1_SN_PCBA_IMEI" PRIMARY KEY ("SERIAL_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "UPDDATA"  ENABLE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "UPDDATA" ;
  
  
    CREATE TABLE "UPD"."UPD_PCBA_PGM_MEID" 
     (	"SERIAL_NO" VARCHAR2(50 BYTE), 
  	"PROTOCOL_NAME" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"AKEY1_TYPE" VARCHAR2(50 BYTE), 
  	"AKEY1_VALUE" VARCHAR2(50 BYTE), 
  	"AKEY2_TYPE" VARCHAR2(50 BYTE), 
  	"AKEY2_VALUE" VARCHAR2(50 BYTE), 
  	"MASTER_SUBLOCK_TYPE" VARCHAR2(50 BYTE), 
  	"MASTER_SUBLOCK_CODE" VARCHAR2(50 BYTE), 
  	"ONETIME_SBLOCK_TYPE" VARCHAR2(50 BYTE), 
  	"ONETIME_SBLOCK_CODE" VARCHAR2(50 BYTE), 
  	"PESN" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"MEID_DECIMAL" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"REQUEST_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"REQUESTER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"GENERATION_DATE" DATE NOT NULL ENABLE, 
  	"GPPD_ID" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"CUSTOMER" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"PROGRAMMING_FACILITY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"BUILD_TYPE" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"PRODUCT_NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
  	"DISPATCH_DATE" DATE, 
  	"DISPATCH_STATUS" CHAR(1 BYTE) NOT NULL ENABLE, 
  	"RSD_ID" VARCHAR2(50 BYTE), 
  	"MASC_ID" VARCHAR2(50 BYTE), 
  	"CLIENT_REQUEST_DATETIME" DATE, 
  	"CREATED_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"CREATED_DATETIME" DATE NOT NULL ENABLE, 
  	"LAST_MOD_BY" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"LAST_MOD_DATETIME" DATE NOT NULL ENABLE, 
  	"PGM_DATE" DATE, 
  	"PGM_STATUS" VARCHAR2(50 BYTE) NOT NULL ENABLE, 
  	"SWAP_DATE" DATE, 
  	"PCBA_ASSEMBLY_PTNO" VARCHAR2(50 BYTE), 
  	 CONSTRAINT "PK_SN_PCBA_MEID" PRIMARY KEY ("SERIAL_NO")
    USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
    STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "UPDDATA"  ENABLE
     ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
    STORAGE(INITIAL 5242880 NEXT 5242880 MINEXTENTS 1 MAXEXTENTS 2147483645
    PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
    TABLESPACE "UPDDATA" ;
	
	CREATE TABLE shipment_notavail_sn
  (
    SERIAL_NO_IN  VARCHAR2(50) NOT NULL,
    SERIAL_NO_OUT VARCHAR2(50) NOT NULL,
    CREATED_BY    VARCHAR2(20) NOT NULL,
    CREATION_DATETIME DATE NOT NULL ,
    LAST_MOD_BY VARCHAR2(20) NOT NULL,
    LAST_MOD_DATETIME DATE NOT NULL,
    STATUS VARCHAR2(50) NOT NULL
    
  ); 
 
 
 REM INSERTING into UPD_CONFIG
 SET DEFINE OFF;
Insert into UPD.UPD_CONFIG (SECTION,KEY,VALUE) values ('PCBA_CONFIG_NEW','CONFIG_NEW','NO');
Insert into UPD.UPD_CONFIG (SECTION,KEY,VALUE) values ('PCBA_CONFIG_OLD','CONFIG_OLD','YES');
 
 commit;
 
